# configuration data

main:
    apikey: your apikey here
    model: gemini-2.0-flash-lite
    common: "plugins/GeminiNPC/common"
    show-system-instructions: false
    attack-notification-duration: 20
    default-npc-respond-prob: 0.1


persona-directories:
    - plugins/GeminiNPC/personae

texts:
    shop-instruction: |
        You are a shopkeeper. Users can right-click you to open your shop.
    location-list-start: "Locations you can go to: "

    no-skylight-time: You are underground and do not know the time.
    no-skylight-weather: You are underground and do not know the weather.
    in-combat-now: You are currently in a fight!

    # these are standard JSON instructions sent to the parser
    standard-system-instructions: |
      {
        "role": "system",
        "rules": [
          "Return ONLY valid JSON that matches the schema.",
          "No comments.",
          "No additional fields.",
          "No trailing commas.",
          "No explanation before or after the JSON."
        ],
        "response_schema": {
          "player": "string",
          "response": "string",
          "command": "string"
        },
        "response_field_descriptions": {
          "player": "The name of the player to whom you are responding, or empty if this is a response to an event.",
          "response": "The chat response. Actions here should be in the form (he/she smiles quietly).",
          "command": "A command to be performed."
        },
        "commands_and_descriptions": {
          "give ITEM": "Give an item to a player. ITEM must be a Minecraft material"
        }
      }
